config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('radio.urls', 'radio')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

radio/urls.py
from django.urls import path

from . import views


app_name = 'radio'


urlpatterns = [
    path('',
         views.HomeView.as_view(), name='home'),
    path('radio/',
         views.RadioListView.as_view(), name='radio-list'),
    path('radio/<slug:slug>/',
         views.RadioDetailView.as_view(), name='radio-detail'),
    path('radio/<slug:slug>/tofavorite/',
         views.AddStationToFavoriteView.as_view(), name='add-to-favorite'),
    path('ganre/',
         views.GanreListView.as_view(), name='ganre-list'),
    path('ganre/<slug:slug>/',
         views.RadioListByGanreView.as_view(), name='ganre-detail'),
    path('favorite/',
         views.RadioListByFavoriteView.as_view(), name='favorite-list'),
]

radio/models.py
from pytils.translit import slugify

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator


class SlugifyMixin:
    slug_field_name: str = 'slug'
    slug_from_field_name: str = 'name'

    def generate_slug(*args) -> str:
        return slugify(str.join(*args))

    def save(self, *args, **kwargs) -> None:
        if not hasattr(self, self.slug_field_name)\
                and hasattr(self.slug_from_field_name):
            return super().save(*args, **kwargs)

        if not getattr(self, self.slug_field_name):

            slug_from_value = getattr(self, self.slug_from_field_name)

            slug = self.generate_slug(slug_from_value)

            setattr(self, self.slug_field_name, slug)

        return super().save(*args, **kwargs)


class Ganre(SlugifyMixin, models.Model):
    name = models.CharField('Название', max_length=100, unique=True,
                            db_index=True)
    slug = models.SlugField(max_length=100, unique=True, db_index=True)

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self) -> str:
        return reverse('radio:ganre-detail', kwargs={'slug': self.slug})


class Radio(SlugifyMixin, models.Model):
    name = models.CharField('Название', max_length=255, db_index=True)
    stream_url = models.URLField('Url потока', db_index=True, unique=True)
    ganre = models.ManyToManyField(verbose_name='Жанр', to=Ganre, blank=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)
    created = models.DateField('Время создания', auto_now_add=True)
    visible = models.BooleanField('Видимость', default=True)
    preview = models\
        .ImageField('Превью', upload_to='previews/', null=True,
                    blank=True,
                    default=f'/{settings.MEDIA_URL}/previews/default.png')

    class Meta:
        verbose_name = 'Радио'
        verbose_name_plural = 'Радио'

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self) -> str:
        return reverse('radio:radio-detail', kwargs={'slug': self.slug})


class Feedback(models.Model):
    username = models.CharField('Имя', max_length=100, db_index=True)
    email = models.EmailField('Электронная почта', db_index=True)
    rating = models.PositiveIntegerField('Оценка', db_index=True,
                                         validators=[MinValueValidator(0),
                                                     MaxValueValidator(5)])
    message = models.TextField('Сообщение', max_length=1000, blank=True,
                               null=True)
    radio = models.ForeignKey(verbose_name='Радио', to=Radio,
                              related_name='feedbacks',
                              on_delete=models.CASCADE)
    created = models.DateTimeField('Дата создания', auto_now_add=True,
                                   db_index=True)

    class Meta:
        verbose_name = 'Оценка'
        verbose_name_plural = 'Оценки'

    def __str__(self) -> str:
        return self.username


GanreQuerySet = models.QuerySet[Ganre]
RadioQuerySet = models.QuerySet[Radio]
FeedbackQuerySet = models.QuerySet[Feedback]

radio/forms.py
from django import forms
from .models import Feedback


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = '__all__'
        exclude = ['radio']

radio/views/mixins.py
from typing import Any

from django.db.models import QuerySet, Q


class SearchMixin:
    search_fileds: list[str] = []
    search_name: str = 'search'

    def get_serch_value(self) -> str:
        return self.request.GET.get(self.search_name)

    def get_queryset(self) -> QuerySet[Any]:
        if hasattr(super(), 'get_queryset'):
            queryset = super().get_queryset()

            print("searching")

            search_value = self.get_serch_value()

            if not search_value:
                return queryset

            fr = [{v: search_value} for v in self.search_fileds]

            f = Q()
            for field in fr:
                f = f.__or__(Q(**field))

            return queryset.filter(f)

radio/templates/radio/base.html
<!DOCTYPE html>
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Radious | {% block subtitle %}Главная{% endblock %}{% endblock %}</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'radio/css/style.css' %}">
    {% block extrastyle %}
    {% endblock %}
</head>
<body>
    <div class="container">
        {% block sidebar %}
            {% include 'radio/sidebar.html' %}
        {% endblock %}
        <div class="right">
            <div class="content_header">
                {% block content_header %}
                {% endblock %}
            </div>
            <main class="main">
                {% block content %}
                {% endblock %}
            </main>
        </div>

        {% load static %}
        <script src="{% static 'radio/js/index.js' %}" type="module"></script>
        {% block extrascript %}
        {% endblock %}
    </div>
</body>
</html>

radio/templates/radio/ganre_list.html
{% extends 'radio/base.html' %}

{% block subtitle %}Поиск по жанру{% endblock %}

{% block content_header %}
<h1 class="content_header__heading">Поиск радиостанций по жанру</h1>
<p class="content_header__description">Слушайте радио онлайн в хорошем качестве, онлайн и без регистрации</p>
{% endblock %}

{% block content %}
<div class="ganre-list">
    {% for item in object_list %}
    <div class="ganre-list__item">
        <h3><a href="{{ item.get_absolute_url }}">{{ item.name }}</a></h3>
    </div>
    {% endfor %}
</div>
{% endblock %}

radio/templates/radio/home.html
{% extends 'radio/base.html' %}


{% block content_header %}
<h1 class="content_header__heading">Слушать радио онлайн</h1>
{% endblock %}

{% block content %}
{% load radio %}
<div class="station_assembly_list">
    <div class="station_assembly_list__item assembly">
        {% include 'radio/inc_radio_list.html' with list_title='Новинки' object_list=object_list|newest %}
    </div>

    <div class="station_assembly_list__item assembly">
        {% include 'radio/inc_radio_list.html' with list_title='Популярные радиостанции' object_list=object_list|popular:10 %}
    </div>
</div>
{% endblock %}

radio/templates/radio/inc_radio_list.html
<h2 class="assembly__naming">{{ list_title }}</h2>
<div class="station_list station_list--horizontal">
    {% for item in object_list %}
    <div class="station_list__item station_list__item--vertical radio-station">
        <img class="radio-station__img" src="{{ item.preview.url }}" width="100" height="100">
        <h4 class="radio-station__naming"><a class="link" href="{% url 'radio:radio-detail' slug=item.slug %}">{{ item.name }}</a></h4>
    </div>
    {% endfor %}
</div>

radio/templates/radio/radio_detail.html
{% extends 'radio/base.html' %}

{% block extrastyle %}
{% load static %}
<link rel="stylesheet" href="{% static 'radio/css/player/style.css' %}">
{% endblock %}

{% block content %}

<div class="radio-station">
    <img src="{{ object.preview.url }}" width="175" height="175">

    <div class="radio-station__content">
        <small>
            <span>Оценка: {{ object.rating }}</span>
            <span><a href="#Feedbacks">Отзывы: {{ object.feedbacks.count }}</a></span>
        </small>
        <h2>{{ object.name }}</h2>
        <ul class="list">
            {% for item in object.ganre.all %}
            <li class="list-item ganre"><a href="{% url 'radio:ganre-detail' slug=item.slug %}">{{ item.name }}</a></li>
            {% endfor %}
        </ul>
    </div>

    <div id="RadioPlayer" class="player" data-stream="{{ object.stream_url }}"></div>
</div>

<div id="Feedbacks">
    <h3>Отзывы о "{{ object.name }}" <small>({{ object.feedbacks.all.count }})</small></h3>

    <button class="toggler" data-target="#NewFeedbackPopup" data-class-name="hidden">Оставить отзыв</button>

    <div id="NewFeedbackPopup" class="popup hidden">
        <div class="popup__content">
            <button class="toggler material-symbols-outlined" data-target="#NewFeedbackPopup" data-class-name="hidden">close</button>
            <form id="feedbackForm" method="post" action="">
                {% csrf_token %}
                {{ form }}
                <input type="submit" value="Отправить">
            </form>
        </div>
    </div>

    <div class="list">
        {% for item in object.feedbacks.all %}
        <div class="list-item feedback">
            <div>
                <h4>{{ item.username }}</h4>
                <small>Оценка: {{ item.rating }}</small>
            </div>
            <p>{{ item.message }}</p>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

radio/templates/radio/radio_list.html
{% extends 'radio/base.html' %}

{% block subtitle %}Список станций{% endblock %}

{% block content_header %}
<h1 class="content_header__heading">Онлайн радио</h1>
<p class="content_header__description">Слушайте радио онлайн в хорошем качестве, онлайн и без регистрации</p>
{% endblock %}


{% block content %}
<div class="station_list">
    {% for item in object_list %}
    <div class="station_list__item radio-station">

        {% load static %}
        <img class="radio-station__img" src="{{ item.preview.url }}" width="75" height="75">

        <h3 class="radio-station__naming"><a class="link" href="{{ item.get_absolute_url }}">{{ item.name }}</a></h3>

        <button id="AddFavoriteButton" class="button material-symbols-outlined" data-id="{{ item.slug }}"s>favorite</button>
    </div>
    {% endfor %}
</div>
{% endblock %}

radio/templates/radio/sidebar.html
<aside class="sidebar">
    <div class="branding">
        <h2 class="branding__logo"><a class="link" href="/">RADIOUS</a></h2>
    </div>
    {% block sidebar_content %}

    <form class="form search_form" id="SearchBox" method="get">
        <input class="input search_form__input" type="text" name="search" id="SearchInput">
        <input class="input material-symbols-outlined" type="submit" value="search" />
    </form>

    <nav class="nav">
        {% url 'radio:radio-list' as radio_list_url %}
        <div class="nav__item {% if radio_list_url == request.path %} nav__item--active {% endif %}"><a class="link" href="{{ radio_list_url }}">Радио</a></div>
        {% url 'radio:ganre-list' as ganre_list_url %}
        <div class="nav__item {% if ganre_list_url == request.path %} nav__item--active {% endif %}"><a class="link" href="{{ ganre_list_url }}">Жанры</a></div>
        {% url 'radio:favorite-list' as favorite_list_url %}
        <div class="nav__item {% if favorite_list_url == request.path %} nav__item--active {% endif %}"><a class="link" href="{{ favorite_list_url }}">Избранное</a></div>
    </nav>
    {% endblock %}
</aside>